Repository shapelets/shapelets-solo-examples, pull requests merged in 2021-07, with the labels that each got.

#11 Feature/selector
  dataapps/Controllers/08_label_advanced.py
  dataapps/Controllers/09_selector.py
  dataapps/Operations/03_load_dataframe_with_time_series.py
Labels: enhancement

#13 Fixed issue with shapelets-solo version
  requirements.txt
Labels: bug

#17 Adding more examples
  dataapps/Operations/04_load_generic_dataframe.py
  dataapps/Operations/05_use_custom_function.py
Labels: documentation

#23 Added support for render title after execution result
  dataapps/Charts/07_linechart_computed.py
Labels: enhancement

#22 Feature/tabs flow panel
  dataapps/Layouts/03_tabs_flow_panel.py
Labels: enhancement

#30 Develop
  dataapps/Charts/07_linechart_computed.py
  dataapps/Charts/07_linechart_with_views.py
  dataapps/Charts/07_scatterplot_example.py
  dataapps/Controllers/10_timer.py
  dataapps/Layouts/03_tabs_flow_panel.py
Labels: enhancement

#33 Add date input example
  dataapps/Controllers/11_date.py
Labels: enhancement
